name: Check formatting (Go)

on: [push, workflow_dispatch]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Go formatting
        run: |
          gofmt -l -s -w .
          git diff --exit-code
